// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsJavaProps")>]
[<assembly: AssemblyProductAttribute("FsJavaProps")>]
[<assembly: AssemblyDescriptionAttribute("FsJavaPropsr")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsJavaProps"
    let [<Literal>] AssemblyProduct = "FsJavaProps"
    let [<Literal>] AssemblyDescription = "FsJavaPropsr"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
